### ISSUE TITLE
Modifying enum name breaks code functionality.

### ISSUE THREAD

**Issue by b-sia** [charmbracelet/kancli#4]
I am refactoring the tutorial KanCLI project, placing the type definitions in a separate package. My goal is to refactor the `Model` and `Form` structs into separate packages. At the same time, there is a name clash between the `Model` and `Form` structs and a predefined Enum.

```go
const (
	Model Status = iota
	Form
)
```
I then renamed the Enum values.

```go
const (
	ModelEnum Status = iota
	FormEnum
)
```
But that broke the task addition feature.

[Here](https://github.com/zerovirus123/cli_kanban/tree/17284c8ae20e3e4debdd754b210d83a81ff8013f) is the repo before the enum modification.

[Here](https://github.com/zerovirus123/cli_kanban/tree/97c79cf2cec47bccaeac7349be11c5c9a021d9be) is the repo after the enum modification.

**Comment by muesli** [comment]
When you say "broke", what does that exactly mean?

One thing that's definitely broken in your repository is the relative import of the typedef package. You need to use canonical import paths, e.g. `import github.com/zerovirus123/cli_kanban/typedef`.

**Comment by b-sia** [comment]
@muesli  The new tasks no longer shows up in the columns.

**Comment by bashbunni** [comment]
Ah so, you changed `NewTask` to return a `*Task` instead of a `Task` (which is fine). So all you need to do to fix this is to make sure that the `case task.Task` in your `model.go` is changed to `case *task.Task`. Made that change on my local copy and have it adding new tasks to the lists without issue. Lmk if you have any more questions!

**Comment by b-sia** [comment]
Resolved the issue on my side. Thanks for the follow up!
